# Generated by Django 5.1.5 on 2025-01-15 05:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_rename_uploadedfile_uploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='cloudinary_id',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='url',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image file', max_length=255, null=True, verbose_name='image'),
        ),
    ]
